### ISSUE TITLE
Remove Cloudflare

### ISSUE THREAD

**Issue by AnXh3L0** [AdAway/adaway.github.io#19] opened 2019-08-26 10:02 UTC
Hi @PerfectSlayer,

Can we please remove Cloudflare from AdAway? GitHub now provides SSL for custom domains so we don't need it anymore. There's also countless privacy issues related to using Cloudflare so I believe this is necessary.

Thanks!

**Comment by AnXh3L0** [comment] 2019-09-06 20:27
@PerfectSlayer any update on this?

Thanks!

**Comment by PerfectSlayer** [comment] 2019-09-08 15:11
I have contacted the support from my hosting company to migrate the adaway.org domain to my account. Once done, I will update the DNS to no more use Cloudfare.

I will keep you posted once done but it will take some days… 😴

**Comment by AnXh3L0** [comment] 2019-09-08 15:11
Thanks, sounds good :)

**Comment by PerfectSlayer** [comment] 2019-09-21 07:08
I just order the domain transfer.
Once applied, I will setup DNS to target github page directly without Cloudfare.

I hope it will not cause issue with hosts file and GitHub hosting 😅

**Comment by AnXh3L0** [comment] 2019-09-21 07:19
Great, it shouldn't cause any issue whatsoever 👍

**Comment by stangri** [comment] 2019-10-03 14:05
Is the current adaway.org downtime caused by the transfer?

**Comment by PerfectSlayer** [comment] 2019-10-05 05:57
Yes! I only got the transfer notice 2 days ago and it's the first time I get free time to fix it (the Saturday at 7am 😭 )
![image](https://user-images.githubusercontent.com/1766222/66250552-89f77880-e744-11e9-82ce-d190dec9f608.png)
I enable DNS zone in OVH control panel. I now need to wait for them to enable it then set the DNS to GitHub pages and wait for DNS record propagation.

So it might still be down for few hours / days... Thanks for the ping @stangri !

**Comment by PerfectSlayer** [comment] 2019-10-05 06:53
It should be up right now! 🎉 
Tell me if everything is all right and close the issue.

**Comment by Veldkornet** [comment] 2019-10-05 07:34
Looks good to me

**Closed** 2019-10-09 19:00 UTC
